name: Build APK
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          openjdk-17-jdk \
          build-essential \
          libssl-dev \
          libffi-dev \
          python3-dev \
          git \
          zip \
          unzip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev
    
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install Cython==0.29.33
        pip install buildozer==1.5.0
    
    - name: Verify files exist
      run: |
        echo "=== Checking project files ==="
        ls -la
        echo "=== Checking buildozer.spec ==="
        if [ -f buildozer.spec ]; then
          echo "✓ buildozer.spec found"
          cat buildozer.spec
        else
          echo "✗ buildozer.spec NOT found!"
          exit 1
        fi
        echo "=== Checking main.py ==="
        if [ -f main.py ]; then
          echo "✓ main.py found"
        else
          echo "✗ main.py NOT found!"
          exit 1
        fi
    
    - name: Build APK
      run: |
        buildozer -v android debug
    
    - name: List bin directory
      if: always()
      run: |
        echo "=== Contents of bin directory ==="
        ls -lah bin/ || echo "bin/ directory not found"
    
    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: IKISKY-VPN-APK
        path: bin/*.apk
        retention-days: 7
    
    - name: Upload build logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          .buildozer/android/platform/build-*/build.log
          .buildozer/android/logs/*
        retention-days: 3
