name: Build APK
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          openjdk-17-jdk \
          build-essential \
          libssl-dev \
          libffi-dev \
          python3-dev \
          git \
          zip \
          unzip
    
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install Cython==0.29.33
        pip install buildozer==1.5.0
    
    - name: Create flags directory
      run: |
        mkdir -p flags
        # Если флаги есть в репозитории, переместите их
        if ls s*.png 1> /dev/null 2>&1; then
          mv s*.png flags/ || true
        fi
    
    - name: Build APK with verbose output
      run: |
        buildozer -v android debug
    
    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: IKISKY-VPN-APK
        path: bin/*.apk
        retention-days: 7
    
    - name: Upload build logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: .buildozer/android/platform/build-*/build.log
        retention-days: 3
