name: Build APK
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache Buildozer
      uses: actions/cache@v3
      with:
        path: |
          ~/.buildozer
          .buildozer
        key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          openjdk-17-jdk \
          build-essential \
          git \
          zip \
          unzip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          cmake \
          libffi-dev \
          libssl-dev \
          python3-dev
    
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade wheel setuptools
        pip install Cython==0.29.33
        pip install buildozer==1.5.0
    
    - name: Verify project structure
      run: |
        echo "Current directory contents:"
        ls -la
        echo ""
        echo "Checking buildozer.spec:"
        if [ -f buildozer.spec ]; then
          echo "✓ Found"
          head -20 buildozer.spec
        else
          echo "✗ Missing - creating default"
          buildozer init
        fi
        echo ""
        echo "Checking main.py:"
        if [ -f main.py ]; then
          echo "✓ Found"
        else
          echo "✗ Missing main.py!"
          exit 1
        fi
    
    - name: Build APK
      run: |
        buildozer android debug --verbose
      timeout-minutes: 180
    
    - name: Show build results
      if: always()
      run: |
        echo "Build directory contents:"
        ls -lah bin/ 2>/dev/null || echo "No bin directory"
        echo ""
        echo "Buildozer directory:"
        du -sh .buildozer 2>/dev/null || echo "No .buildozer directory"
    
    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: IKISKY-VPN-APK
        path: bin/*.apk
        retention-days: 7
    
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          .buildozer/android/platform/build-*/build.log
          .buildozer/android/logs/*.log
        retention-days: 3
        if-no-files-found: warn
